# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_portofolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portofolio',
            options={'ordering': ['-created'], 'verbose_name': 'Portofolio Entry', 'verbose_name_plural': 'Portofolio Entries'},
        ),
    ]
