# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160307_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contain', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Slider Benny Danang K',
                'verbose_name_plural': 'Slider Entries',
            },
        ),
        migrations.DeleteModel(
            name='Input',
        ),
        migrations.AlterModelOptions(
            name='portofolio',
            options={'ordering': ['-created'], 'verbose_name': 'Portofolio Benny Danang K', 'verbose_name_plural': 'Portofolio Entries'},
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
